stages:
  - build
  - deploy
build:
  stage: build
  image: maven:3.8.6-openjdk-8
  script:
    - echo "Building app..."
    - mvn clean install
    - echo "Finished building the app."
  artifacts:
    expire_in: 1 week
    paths:
      - target/h1b_extension_api.jar
  only:
    - master
deploy:
  stage: deploy
  image: alpine:3.11
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying started..."
    - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop h1b_extension_api.service"
    - scp ./target/h1b_extension_api.jar ubuntu@$DEPLOY_SERVER_IP:~/h1b-extension-api/
    - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start h1b_extension_api.service"
    - echo "Finished deploying the app"
  only:
    - master