# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven


name: H1B Extension API CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      env: 
        DB_HOST: ${{ secrets.H1B_RDS_HOST }}
      run: mvn -B package --file pom.xml

    - name: Execute JAR file
      run: sudo java -jar /home/ubuntu/actions-runner/_work/h1b_extension_api/h1b_extension_api/target/h1b_extension_api.jar
